# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and Deploy Employee Task API

on:
  push:
    branches:
      - master
    paths:
      - 'Service/**'
      - '.github/workflows/service_workflow.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Packages
        run: dotnet restore Service/EmployeeTaskManagement.API/EmployeeTaskManagement.API.csproj

      - name: Build
        run: dotnet build Service/EmployeeTaskManagement.API/EmployeeTaskManagement.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Service/EmployeeTaskManagement.API/EmployeeTaskManagement.API.csproj --configuration Release --no-build --output "${{ github.workspace }}/publish"

      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Publish Artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0E8DF30F77EB48FABB14FDF19EFB0409 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FF0C76C90C994D8C862793AF5408318E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_66F53964CFEE45C5B05A98B8A87F2881 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: employee-task-api
          slot-name: Production
          package: publish
